apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
data:
  MYSQL_PASS: cGFzc3dvcmQ=        # "password" base64
  FLASK_SECRET_KEY: c3VwZXItc2VjcmV0LQ==  # "super-secret-" in base64
